### ISSUE TITLE
a newer version of google_mlkit_text_recognition that supports GoogleDataTransport (~> 10.0)

### ISSUE THREAD

**Issue by matheuss-2001** [flutter-ml/google_ml_kit_flutter#669] opened 2024-08-27 15:49 UTC
a newer version of google_mlkit_text_recognition that supports GoogleDataTransport (~> 10.0).

Firebase just update their package requires GoogleDataTransport (~> 10.0) , however google_mlkit_text_recognition depends on an earlier version of GoogleDataTransport (< 10.0). it caused conflict . I'm unable to install my pod commands in project.

**Comment by AndreyDAraya** [comment] 2024-08-27 17:33
Problems with firebase-core:
In Podfile:
    firebase_analytics (from `.symlinks/plugins/firebase_analytics/ios`) was resolved to 11.3.0, which depends on
      Firebase/Analytics (= 11.0.0) was resolved to 11.0.0, which depends on
        Firebase/Core (= 11.0.0) was resolved to 11.0.0, which depends on
          FirebaseAnalytics (~> 11.0.0) was resolved to 11.0.0, which depends on
            nanopb (~> 3.30910.0)

    google_mlkit_barcode_scanning (from `.symlinks/plugins/google_mlkit_barcode_scanning/ios`) was resolved to 0.12.0, which depends on
      GoogleMLKit/BarcodeScanning (~> 6.0.0) was resolved to 6.0.0, which depends on
        GoogleMLKit/MLKitCore (= 6.0.0) was resolved to 6.0.0, which depends on
          MLKitCommon (~> 11.0.0) was resolved to 11.0.0, which depends on
            GoogleDataTransport (< 10.0, >= 9.4.1) was resolved to 9.4.1, which depends on
              nanopb (< 2.30911.0, >= 2.30908.0)

Some fix?

**Comment by tomasatisocco** [comment] 2024-08-27 21:26
I'm also looking for a fix for this

**Comment by fbernaly** [comment] 2024-08-27 21:47
send a PR and I will review, contributions are always welcome and easier to release.

**Comment by AndreyDAraya** [comment] 2024-08-27 21:50
https://github.com/google/GoogleDataTransport/issues/149

I open new issue, directly in GoogleDataTransport..
I feel that they must be update  the version of nanopb

**Comment by matheuss-2001** [comment] 2024-08-28 16:31
I solved my problem downgrading my firebase versions  to be compatible to google_mlkit_text_recognition -   
  firebase_messaging: '15.0.0'
  firebase_core: '3.0.0'
  firebase_auth: '5.0.0'
  # firebase_analytics: '11.0.0'
  firebase_dynamic_links: ^6.0.0
  cloud_firestore: '5.0.0'
  firebase_storage: '12.0.0'

**Comment by AndreyDAraya** [comment] 2024-08-28 17:52
The fix, I talk with Google member and recommend this actions:

https://github.com/google/GoogleDataTransport/issues/149#issuecomment-2313898323

firebase_core: ^2.32.0
firebase_remote_config: ^4.4.7
firebase_analytics: ^10.10.7
...Other packages

Or the version old 3 month.  
While google_ml_kit_flutter update  GoogleDataTransport

**Comment by tomasatisocco** [comment] 2024-08-28 22:42
> The fix, I talk with Google member and recommend this actions:
> 
> [google/GoogleDataTransport#149 (comment)](https://github.com/google/GoogleDataTransport/issues/149#issuecomment-2313898323)
> 
> firebase_core: ^2.32.0 firebase_remote_config: ^4.4.7 firebase_analytics: ^10.10.7 ...Other packages
> 
> Or the version old 3 month. While google_ml_kit_flutter update GoogleDataTransport

Yeah I locked those version as a workaround in the meanwhile

**Comment by bensonarafat** [comment] 2024-08-29 01:56
> send a PR and I will review, contributions are always welcome and easier to release.

There are no mlkit updates for ios yet

**Comment by michaelnabil230** [comment] 2024-09-03 11:13
I have the same problem

**Comment by adilelli** [comment] 2024-09-05 09:09
I'm having this issue

[!] CocoaPods could not find compatible versions for pod "GoogleDataTransport":
  In Podfile:
    firebase_messaging (from `.symlinks/plugins/firebase_messaging/ios`) was resolved to 15.1.0, which depends on
      Firebase/Messaging (= 11.0.0) was resolved to 11.0.0, which depends on
        FirebaseMessaging (~> 11.0.0) was resolved to 11.0.0, which depends on
          GoogleDataTransport (~> 10.0)

    mobile_scanner (from `.symlinks/plugins/mobile_scanner/ios`) was resolved to 5.2.1, which depends on
      GoogleMLKit/BarcodeScanning (~> 6.0.0) was resolved to 6.0.0, which depends on
        MLKitBarcodeScanning (~> 5.0.0) was resolved to 5.0.0, which depends on
          MLKitCommon (~> 11.0) was resolved to 11.0.0, which depends on
            GoogleDataTransport (< 10.0, >= 9.4.1)

**Comment by harry-dickson** [comment] 2024-09-07 08:23
@fbernaly 
> send a PR and I will review, contributions are always welcome and easier to release.

That's easy for a `Collaborator` to say 😉 I wouldn't have a clue where to start on that...

Without changing my pubspec.yaml I did `pub upgrade` (always good to get bugfixes?) and things broke. So now I have to downgrade a bunch of stuff??

The flutter/firebase/google ecosystem isn't quite as joined up and tested as us poor confused app developers would like.

Sorry this is mostly an unhelpful rant. (but it helped me; to feel better)

**Comment by BigMenya** [comment] 2024-09-09 13:44
Yeah faced unexpectedly when cleared build cache.
That worked for me: 
yaml:
firebase_core: ^2.31.0
firebase_analytics: ^10.10.7
firebase_crashlytics: ^3.5.7
firebase_messaging: ^14.9.2

in ios folder:
pod install --repo-update
pod update Firebase/CoreOnly

**Comment by phluidaungyezaw** [comment] 2024-09-18 21:13
same issue

firebase_analytics: Using Firebase SDK version '11.0.0' defined in 'firebase_core'
firebase_auth: Using Firebase SDK version '11.0.0' defined in 'firebase_core'
firebase_core: Using Firebase SDK version '11.0.0' defined in 'firebase_core'
Warning: firebase_app_id_file.json file does not exist. This may cause issues in upload-symbols. If this error is unexpected, try running flutterfire configure again.
firebase_crashlytics: Using Firebase SDK version '11.0.0' defined in 'firebase_core'
firebase_dynamic_links: Using Firebase SDK version '11.0.0' defined in 'firebase_core'
firebase_messaging: Using Firebase SDK version '11.0.0' defined in 'firebase_core'
[!] CocoaPods could not find compatible versions for pod "GoogleDataTransport":
  In Podfile:
    firebase_crashlytics (from `.symlinks/plugins/firebase_crashlytics/ios`) was resolved to 4.1.2, which depends on
      Firebase/Crashlytics (= 11.0.0) was resolved to 11.0.0, which depends on
        FirebaseCrashlytics (~> 11.0.0) was resolved to 11.0.0, which depends on
          GoogleDataTransport (~> 10.0)

    google_mlkit_text_recognition (from `.symlinks/plugins/google_mlkit_text_recognition/ios`) was resolved to 0.13.0, which depends on
      GoogleMLKit/TextRecognition (~> 6.0.0) was resolved to 6.0.0, which depends on
        GoogleMLKit/MLKitCore (= 6.0.0) was resolved to 6.0.0, which depends on
          MLKitCommon (~> 11.0.0) was resolved to 11.0.0, which depends on
            GoogleDataTransport (< 10.0, >= 9.4.1)
            
  google_mlkit_text_recognition: ^0.13.0
  firebase_analytics: 11.0.0
  firebase_core: 3.5.0
  firebase_messaging: 15.1.2
  firebase_dynamic_links: 6.0.7
  firebase_auth: 5.3.0
  firebase_crashlytics: 4.1.2
  
Flutter 3.24.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2663184aa7 (7 days ago) • 2024-09-11 16:27:48 -0500
Engine • revision 36335019a8
Tools • Dart 3.5.3 • DevTools 2.37.3

**Comment by ueman** [comment] 2024-09-19 08:26
Duplicate of https://github.com/flutter-ml/google_ml_kit_flutter/issues/675, in particular see https://github.com/flutter-ml/google_ml_kit_flutter/issues/675#issuecomment-2360302610

**Comment by Doublon** [comment] 2024-09-20 07:59
So no news, it’s starting to become blocking. I can't release a version of my app...

**Comment by mauriziopinotti** [comment] 2024-09-20 08:22
> So no news, it’s starting to become blocking. I can't release a version of my app...
It _is_ blocking, not just starting to be.
However, for now the only way is to downgrade firebase and stick the old MLKit stack. 
In my understanding the "root" issue is this: https://issuetracker.google.com/issues/362452861
So the best we can do is comment there to have Google fix it sooner rather than later.

**Comment by fbernaly** [comment] 2024-09-20 14:35
This is outside of our scope, we do not manage dependencies between the different Google's native frameworks. Posting here won't surface the issue to Google. This plugin is not supported by Google. Post in Google's threads to let them know about the issue and that it is blocking your app. This plugin only consumes Google's native dependencies and expose them to Flutter, but the authors of this plugin do not have access to the native source code of those dependencies.

**Comment by bcaspe** [comment] 2024-09-20 14:42
For what it's worth, I got it working with this pubspec.yaml. Basically
what other posters are saying, to downgrade firebase.

#firebase packages
  firebase_core: 3.1.0
  firebase_auth: 5.1.0
  firebase_storage: 12.0.1
  firebase_analytics: 11.0.1
  firebase_crashlytics: 4.0.1
  cloud_firestore: 5.0.1
  cloud_functions: 5.0.1
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.0.0
  google_mlkit_text_recognition: ^0.13.0

**Comment by bahadirarslan** [comment] 2024-09-28 11:59
Someone opened an issue to Google update MLKitCommons dependencies
https://github.com/googlesamples/mlkit/issues/877

**Comment by vietstone-ng** [comment] 2024-10-01 02:29
I'm facing this issue too. Xcode 16 requires the latest firebase packages, but google_mlkit_text_recognition is blocking it

**Comment by rusudinu** [comment] 2024-10-01 06:21
> I'm facing this issue too. Xcode 16 requires the latest firebase packages, but google_mlkit_text_recognition is blocking it

you can use this in order to use the older version of the firebase libraries with xcode 16 (Build Settings -> Apple Clang - Language - Modules -> set Allow Non-modular includes in Framework Modules to 'Yes):
![image](https://github.com/user-attachments/assets/aad21bbb-5bbe-4b36-82c4-715ec7680a0d)

**Comment by vallerydelexy** [comment] 2024-10-01 07:36
> > I'm facing this issue too. Xcode 16 requires the latest firebase packages, but google_mlkit_text_recognition is blocking it
> 
> you can use this in order to use the older version of the firebase libraries with xcode 16 (Build Settings -> Apple Clang - Language - Modules -> set Allow Non-modular includes in Framework Modules to 'Yes): ![image](https://private-user-images.githubusercontent.com/35799602/372342518-aad21bbb-5bbe-4b36-82c4-715ec7680a0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3NjgzNjQsIm5iZiI6MTcyNzc2ODA2NCwicGF0aCI6Ii8zNTc5OTYwMi8zNzIzNDI1MTgtYWFkMjFiYmItNWJiZS00YjM2LTgyYzQtNzE1ZWM3NjgwYTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDA3MzQyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0NjRiZWU1ODUzYzIxM2MxOGIzYTkxZjZlYmRlN2QyNjk2OWYzZTdiNWYyMjExNDIwNGYwZTMwMzk4NGNhMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.beqdpejcVOePZooog-TxvmIwdhBW8PUwxZy92_R7yh4)

well thats not a fix, its just workaround with unknown consequences.

**Comment by harry-dickson** [comment] 2024-10-01 08:12
Go to the [Google Issue](https://issuetracker.google.com/issues/362452861) and hit the `+1`  (I am impacted) at the top
Mayeb leave a comment. Hopefully they will notice it eventually - it is stuck in their `P4` bucket at the moment

**Comment by OutdatedGuy** [comment] 2024-10-04 14:41
The `MLKitCommon` and other `GoogleMLKit` dependencies are now upgraded. Just need to update the flutter packages.

I believe [this PR](https://github.com/flutter-ml/google_ml_kit_flutter/pull/693) will fix the issue.

**Comment by Xim-ya** [comment] 2024-10-07 04:52
> The `MLKitCommon` and other `GoogleMLKit` dependencies are now upgraded. Just need to update the flutter packages.
> 
> I believe [this PR](https://github.com/flutter-ml/google_ml_kit_flutter/pull/693) will fix the issue.

I tested with this dependency changes, and thanks to it, I was able to resolve the related issues. I'm really grateful.

**Comment by muhammednazil** [comment] 2024-10-07 12:11
I upgrade the google_mlkit_face_detection: ^0.11.1 my pod is not updating it gives an error like below 

[!] CocoaPods could not find compatible versions for pod "GoogleDataTransport":
  In snapshot (Podfile.lock):
    GoogleDataTransport (= 10.1.0, ~> 10.0)

  In Podfile:
    firebase_messaging (from `.symlinks/plugins/firebase_messaging/ios`) was resolved to 15.1.0, which depends on
      Firebase/Messaging (= 11.0.0) was resolved to 11.0.0, which depends on
        FirebaseMessaging (~> 11.0.0) was resolved to 11.0.0, which depends on
          GoogleDataTransport (~> 10.0)

    google_mlkit_commons (from `.symlinks/plugins/google_mlkit_commons/ios`) was resolved to 0.8.1, which depends on
      MLKitVision was resolved to 0.60.0, which depends on
        MLKitCommon (~> 0.60) was resolved to 0.61.0, which depends on
          GoogleDataTransport (~> 3.2)


You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * changed the constraints of dependency `GoogleDataTransport` inside your development pod `google_mlkit_commons`.
   You should run `pod update GoogleDataTransport` to apply changes you've made.

**Comment by vietstone-ng** [comment] 2024-10-08 03:11
It's resolved with `google_mlkit_text_recognition: 0.14.0`. And set the minimum iOS target to 15.5.

**Comment by bensonarafat** [comment] 2024-10-23 13:05
We can close this now! 👍

**Closed by bensonarafat** 2024-10-23 13:05 UTC
Labels: Out of scope, Text Recognition, dependencies
