### ISSUE TITLE
CocoaPods Dependency Conflict: Incompatible Versions for nanopb (Firebase Dependency)

### ISSUE THREAD

**Issue by simeonangelov94** [flutter-ml/google_ml_kit_flutter#676] opened 2024-09-12 07:58 UTC
Can you please check I am using 

google_mlkit_object_detection: ^0.13.0
cloud_firestore: ^5.0.2

For some reason nanopb has a conflict and cannot run the project together?

   Error Code
   
    Resolving dependencies of `Podfile`
    [!] CocoaPods could not find compatible versions for pod "nanopb":
      In Podfile:
        cloud_firestore (from `.symlinks/plugins/cloud_firestore/ios`) was resolved to 5.0.2, which depends on
          Firebase/Firestore (= 11.0.0) was resolved to 11.0.0, which depends on
            FirebaseFirestore (~> 11.0.0) was resolved to 11.0.0, which depends on
              FirebaseFirestoreInternal (= 11.0.0) was resolved to 11.0.0, which depends on
                nanopb (~> 3.30910.0)

        google_mlkit_object_detection (from `.symlinks/plugins/google_mlkit_object_detection/ios`) was resolved to 0.13.0, which depends on
          GoogleMLKit/ObjectDetectionCustom (~> 6.0.0) was resolved to 6.0.0, which depends on
            MLKitObjectDetectionCustom (~> 5.0.0) was resolved to 5.0.0, which depends on
              MLKitCommon (~> 11.0) was resolved to 11.0.0, which depends on
                GoogleDataTransport (< 10.0, >= 9.4.1) was resolved to 9.4.1, which depends on
                  nanopb (< 2.30911.0, >= 2.30908.0)

    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:317:in `raise_error_unless_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:299:in `block in unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:297:in `tap'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:297:in `unwind_for_conflict'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:700:in `attempt_to_filter_existing_spec'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:672:in `attempt_to_activate'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:254:in `process_topmost_state'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/resolver.rb:94:in `resolve'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer/analyzer.rb:1082:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer/analyzer.rb:1080:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer/analyzer.rb:125:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:422:in `analyze'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:244:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:243:in `resolve_dependencies'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/installer.rb:162:in `install!'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/command/install.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.15.2/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:23:in `load'
    /usr/local/bin/pod:23:in `<main>'

**Comment by simeonangelov94** [comment] 2024-09-12 10:50
@eitoball @hovadur @RomainFranceschini @panmari

**Comment by kamranbekirovyz** [comment] 2024-09-13 20:15
Following

**Comment by r-dev-limited** [comment] 2024-09-14 22:34
That happens EVERY time they update versions...

**Comment by aswathyMVP** [comment] 2024-09-18 15:34
`[!] CocoaPods could not find compatible versions for pod "GoogleDataTransport":
  In Podfile:
    firebase_messaging (from `.symlinks/plugins/firebase_messaging/ios`) was resolved to 15.1.2, which depends on
      Firebase/Messaging (= 11.0.0) was resolved to 11.0.0, which depends on
        FirebaseMessaging (~> 11.0.0) was resolved to 11.0.0, which depends on
          GoogleDataTransport (~> 10.0)

    google_mlkit_text_recognition (from `.symlinks/plugins/google_mlkit_text_recognition/ios`) was resolved to 0.13.0, which depends on
      GoogleMLKit/TextRecognition (~> 6.0.0) was resolved to 6.0.0, which depends on
        MLKitTextRecognition (~> 4.0.0) was resolved to 4.0.0, which depends on
          MLKitCommon (~> 11.0) was resolved to 11.0.0, which depends on
            GoogleDataTransport (< 10.0, >= 9.4.1)` 

I am also facing the same issue @bensonarafat

**Comment by ueman** [comment] 2024-09-19 08:26
Duplicate of https://github.com/flutter-ml/google_ml_kit_flutter/issues/675, in particular see https://github.com/flutter-ml/google_ml_kit_flutter/issues/675#issuecomment-2360302610

**Closed** 2024-09-19 10:08 UTC
