### ISSUE TITLE
iOS: Crash when input image is cropped (Barcode scanning)

### ISSUE THREAD

**Issue by g123k** [flutter-ml/google_ml_kit_flutter#255] opened 2022-05-18 12:40 UTC
On [SmoothApp](https://github.com/openfoodfacts/smooth-app), we use your dependency to detect barcodes.
We have an algorithm that allows to [crop the image](https://github.com/openfoodfacts/smooth-app/blob/develop/packages/smooth_app/lib/pages/scan/camera_image_cropper.dart), which works well on Android.

However on iOS, it seems that if the image is not the "full" one, the app will crash:

```
* thread #8, queue = 'ProviderImageSurfaceCacheQueue', stop reason = EXC_BAD_ACCESS (code=1, address=0x154f88000)
    frame #0: 0x000000021e1efb0c libsystem_platform.dylib`_platform_memmove + 188
libsystem_platform.dylib`_platform_memmove:
->  0x21e1efb0c <+188>: ldnp   q0, q1, [x1]
    0x21e1efb10 <+192>: add    x1, x1, #0x20
    0x21e1efb14 <+196>: subs   x2, x2, #0x20
    0x21e1efb18 <+200>: b.hi   0x21e1efb04               ; <+180>
Target 0: (Runner) stopped.
```

**Comment by fbernaly** [comment] 2022-05-18 18:02
@g123k: I am glad you are using our plugin in your app. Could you provide more details? Steps to reproduce? I cloned you [repo](https://github.com/openfoodfacts/smooth-app) and tried to run your app, but first I got issues with the Flutter version, I was using `2.10.5` and was not able con run `flutter pub get` successfully. After I updated my Flutter version to `2.13.0` I was able to run `flutter pub get`. You are using packages that require a minimum Flutter version, for that reason I think you need to include that minimum version in you yaml file as well, so that other devs no what version to use in their envs, something like this:

```ymal
environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.12.0'
```

After resolving that I tried to run the app in Android and getting this issue:

```
"zh": 2 untranslated message(s).
"zu": 2 untranslated message(s).
To see a detailed report, use the untranslated-messages-file 
option in the l10n.yaml file:
untranslated-messages-file: desiredFileName.txt
<other option>: <other selection> 


This will generate a JSON format file containing all messages that 
need to be translated.
Launching lib/main.dart on Pixel 4 in debug mode...
Running Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Gradle could not start your build.
> Cannot create service of type TaskExecuter using method ProjectExecutionServices.createTaskExecuter() as there is a problem with parameter #14 of type ReservedFileSystemLocationRegistry.
   > Cannot create service of type ReservedFileSystemLocationRegistry using method ProjectExecutionServices.createReservedFileLocationRegistry() as there is a problem with parameter #1 of type List<ReservedFileSystemLocation>.
      > Could not create service of type ExecutionHistoryStore using ExecutionGradleServices.createExecutionHistoryStore().
         > Cannot lock execution history cache (~/workspace/smooth-app/packages/smooth_app/android/.gradle/7.4/executionHistory) as it has already been locked by this process.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
Exception: Gradle task assembleDebug failed with exit code 1

```

How can I run the app in Android? Also, could you provide steps to reproduce and get to the scanning barcode functionality? I am willing to help and contribute to you project but need more details.

**Comment by fbernaly** [comment] 2022-05-18 23:49
@g123k: I was not able to run your app, but after looking at your code and learning how you are using the plugin and cropping the `CameraImage`, I created a branch in my example app, I copied your `CameraImageCropper`, and added an overlay to differentiate the area that is actively scanning (cropping area) and I found 2 issues with your code.

**Issue 1**

I think that Y′UV420p (and Y′V12 or YV12) to RGB888 conversion is not needed for iOS or should be different from what you have in your code:

https://github.com/openfoodfacts/smooth-app/blob/develop/packages/smooth_app/lib/pages/scan/camera_image_cropper.dart#L69-L74


`cameraImage.format.raw` returns a different value for iOS and Android:

```
final inputImageFormat InputImageFormatValue.fromRawValue(cameraImage.format.raw);
```

For iOS you get:

```
inputImageFormat: InputImageFormat.bgra8888
```

For Android:

```
inputImageFormat: InputImageFormat.yuv_420_888
```

Therefore you need to modify how to `getBytes()`: https://github.com/openfoodfacts/smooth-app/blob/develop/packages/smooth_app/lib/pages/scan/camera_image_cropper.dart#L81-L107.


**Issue 2**

I think the way you are traversing the planes in `getBytes()` is cropping the wrong area.

https://github.com/openfoodfacts/smooth-app/blob/develop/packages/smooth_app/lib/pages/scan/camera_image_cropper.dart#L89-L105

Once I copied your code (`CameraImageCropper`) in my example app I was defining the same cropping area you have in your app, https://github.com/openfoodfacts/smooth-app/blob/develop/packages/smooth_app/lib/pages/scan/mkit_scan_helper.dart#L258-L261:

```
left01: 0,
top01: 0,
width01: 1,
height01: .5,
```

However, after that I continue testing on Android with different cropping area, for example:

```
left: 0,
top: 0.5,
width: 0.5,
height: 0.5,
```

That will crop the bottom left quadrant, however `CameraImageCropper` is cropping the bottom right quadrant. Look at this image, cropping area is marked with green border, but it detects the QR code only when it is in the other quadrant.

![Screenshot_20220518-162946](https://user-images.githubusercontent.com/7014968/169171726-1f746eda-cffe-4538-8ac0-2fdc1cc6ad9e.png)

After processing the image I am drawing the `cornerPoints` of the barcode in the correct quadrant. In general when the cropping is not horizontally centered your `getBytes()` method inside `CameraImageCropper` is traversing the bytes incorrectly and cropping the wrong area. Since the cropping area you are using in your app is horizontally symmetric you did not encountered this issue before.

To wrap it up, I think you need to fix issue 1: how to crop in iOS, because so far your cropping algorithm only works on Android. You are treating the planes and image data the same way in both iOS and Android, but they should be different because they are different formats. That is why it is crashing in iOS. Cropping the CameraImage is outside the scope of this plugin. Once you fix your cropping area method, your app will work on iOS.

In regards to issue 2, since you are using a horizontally symmetric cropping area you can live with it. However, it would be nice if you fix it as well.

Here you have my branch I tweak with your code:  https://github.com/bharat-biradar/Google-Ml-Kit-plugin/tree/feature/cropping

I hope this helps.

**Comment by renanyoy** [comment] 2022-06-01 09:27
I have same crash in our app on ios but without any cropping.. it works on android.

```
flutter: |L2K|camera initialized
Initialized TensorFlow Lite runtime.
INFO: Initialized TensorFlow Lite runtime.
* thread #2, queue = 'ProviderImageSurfaceCacheQueue', stop reason = EXC_BAD_ACCESS (code=1, address=0x2ade7c000)
libsystem_platform.dylib`_platform_memmove:
->  0x22b44fb0c <+188>: ldnp   q0, q1, [x1]
    0x22b44fb10 <+192>: add    x1, x1, #0x20
    0x22b44fb14 <+196>: subs   x2, x2, #0x20
    0x22b44fb18 <+200>: b.hi   0x22b44fb04               ; <+180>
```

```
  InputImageFormat get processingFormat => Platform.isAndroid
      ? InputImageFormat.yuv_420_888
      : InputImageFormat.yuv420;
  ImageFormatGroup get cameraFormat => ImageFormatGroup.yuv420;

 Future<void> processImage(
      TextRecognizer textRecognizer, CameraImage image) async {
    final size = Size(image.width.toDouble(), image.height.toDouble());
    final pmetas = image.planes
        .map((p) => InputImagePlaneMetadata(
            bytesPerRow: p.bytesPerRow, width: p.width, height: p.height))
        .toList();
    final ii = InputImage.fromBytes(
        bytes: image.planes.first.bytes,
        inputImageData: InputImageData(
            size: size,
            imageRotation: InputImageRotation.rotation90deg,
            inputImageFormat:
                InputImageFormatValue.fromRawValue(image.format.raw) ??
                    processingFormat,
            planeData: pmetas));
    final t = await textRecognizer.processImage(ii);
    blocks.clear();
    blocks.addAll(
        _Block.from(t.blocks, 1 / size.shortestSide, 1 / size.longestSide));
    if (mounted) setState(() {});
  }
```

**Comment by fbernaly** [comment] 2022-06-01 16:13
@renanyoy: are hardcoding `processingFormat` and setting the wrong format for iOS, the format for iOS should be `InputImageFormat.bgra8888`.

I also copied your code in our example app and it is running with no crash. I replaced my method for `_processCameraImage` with you code and it is working, no crash. So, I think it should be something else in your project.

**Comment by renanyoy** [comment] 2022-06-02 06:50
thank you for your reply
I'm wondering if it's maybe a problem with the camera addon 0.9.7+1

on iOS brga I get that
```
Initialized TensorFlow Lite runtime.
INFO: Initialized TensorFlow Lite runtime.
* thread #43, name = 'drishti/0', stop reason = EXC_BAD_ACCESS (code=1, address=0x38)
    frame #0: 0x000000010811a194 Runner`ocr::photo::ImageUtil::PixConvertRGBToLuminance(Pix const*) + 76
Runner`ocr::photo::ImageUtil::PixConvertRGBToLuminance:
->  0x10811a194 <+76>: ldr    x23, [x22, #0x38]
    0x10811a198 <+80>: ldr    w8, [x20, #0x10]
    0x10811a19c <+84>: lsl    w1, w8, #2
    0x10811a1a0 <+88>: ldr    w8, [x22, #0x10]
```

and on android yuv
```
I/flutter ( 3392): |L2K|PlatformException(error, Image dimension, ByteBuffer size and format don't match. Please check if the ByteBuffer is in the decalred format., null, java.lang.IllegalArgumentException: Image dimension, ByteBuffer size and format don't match. Please check if the ByteBuffer is in the decalred format.
```

**Comment by renanyoy** [comment] 2022-06-02 07:24
thank you @fbernaly for your reply.
in fact my code wasn't working anymore with last camera 0.9.7+1 addon on android too
I fixed with this code
```
  Future<void> processImage(
      TextRecognizer textRecognizer, CameraImage image) async {
    final WriteBuffer allBytes = WriteBuffer();
    for (final Plane plane in image.planes) {
      allBytes.putUint8List(plane.bytes);
    }
    final bytes = allBytes.done().buffer.asUint8List();
    final size = Size(image.width.toDouble(), image.height.toDouble());
    final processingFormat =
        InputImageFormatValue.fromRawValue(image.format.raw)!;
    final pmetas = image.planes.map(
      (Plane plane) {
        return InputImagePlaneMetadata(
          bytesPerRow: plane.bytesPerRow,
          height: plane.height,
          width: plane.width,
        );
      },
    ).toList();
    final ii = InputImage.fromBytes(
        bytes: bytes,
        inputImageData: InputImageData(
            size: size,
            imageRotation: InputImageRotation.rotation90deg,
            inputImageFormat: processingFormat,
            planeData: pmetas));
    final t = await textRecognizer.processImage(ii);
    blocks.clear();
    blocks.addAll(
        _Block.from(t.blocks, 1 / size.shortestSide, 1 / size.longestSide));
    if (mounted) setState(() {});
  }
```
and iOS works too in yuv, still crashing if I setup brga for the camera..

**Comment by hidenxtt2001** [comment] 2023-02-18 16:53
@renanyoy do you have any update for this problem with brga format ?

**Comment by renanyoy** [comment] 2023-02-19 08:48
nope, I still use same code, brga for one platform and yuv on the other

**Comment by thanhnn-bap-jp** [comment] 2023-05-10 10:14
I figured out that image.width and image.height values can be zero, so I block the code if image.width == 0 or image.height == 0.

`Future _processCameraImage( CameraImage image, CameraDescription camera) async {
      if (image.width == 0 || image.height == 0) return;
}
`

**Closed** 2023-06-26 18:41 UTC
Labels: Barcode Scanning, InputImage
